workdir: /data/mengxf/Project/JML20240806_tcr_pipeline/result/24080701

samples:
  - test1
  - test2

threads:
  high: 24
  low: 12

software:
  fastqc: /home/mengxf/miniforge3/envs/basic/bin/fastqc
  fastp: /home/mengxf/miniforge3/envs/basic/bin/fastp
  flash: /home/mengxf/miniforge3/envs/basic/bin/flash
  seqkit: /home/mengxf/miniforge3/envs/basic/bin/seqkit
  igblast: /home/mengxf/miniforge3/envs/basic/bin/igblastn
  csvtk: /home/mengxf/miniforge3/envs/basic/bin/csvtk

database:
  germline_db_V: /data/mengxf/Database/IMGT/2024.07/Homo_sapiens/TR/igblast/human_TRBV.fa
  germline_db_D: /data/mengxf/Database/IMGT/2024.07/Homo_sapiens/TR/igblast/human_TRBD.fa
  germline_db_J: /data/mengxf/Database/IMGT/2024.07/Homo_sapiens/TR/igblast/human_TRBJ.fa
  auxiliary_data: /home/mengxf/miniforge3/envs/basic/share/igblast/optional_file/human_gl.aux
