# snakemake -c 32 -s JML-TCR/wf-igblast/Snakefile --configfile JML-TCR/template/snakemake_config.yaml

######## Config ########
workdir: config['workdir']
shell.executable("/bin/bash")
shell.prefix("set +eu; ")

######## Target ########
rule all:
    input:
        expand('1.qc/{sample}/before',sample=config['samples']),
        expand('1.qc/{sample}/after',sample=config['samples']),
        expand('6.figure/{sample}.displot.png',sample=config['samples']),
        expand('6.figure/{sample}.heatmap.png',sample=config['samples'])

######## Modules ########
include: 'rules/fastqc.smk'
include: 'rules/fastp.smk'
include: 'rules/flash.smk'
include: 'rules/concat.smk'
include: 'rules/fq2fa.smk'
include: 'rules/rmdup.smk'
include: 'rules/igblast.smk'
include: 'rules/stats.smk'
include: 'rules/plot.smk'

# TODO 生成单样本报告
