######## Config ########
workdir: config['workdir']
shell.executable("/bin/bash")
shell.prefix("set +eu; ")

######## Target ########
rule all:
    input:
        expand('{sample}/1.qc/before',sample=config['samples']),
        expand('{sample}/1.qc/after',sample=config['samples']),
        expand('{sample}/6.figure/displot.png',sample=config['samples']),
        expand('{sample}/6.figure/heatmap.png',sample=config['samples'])

######## Modules ########
include: 'rules/fastqc.smk'
include: 'rules/fastp.smk'
include: 'rules/flash.smk'
include: 'rules/concat.smk'
include: 'rules/fq2fa.smk'
include: 'rules/rmdup.smk'
include: 'rules/igblast.smk'
include: 'rules/stats.smk'
include: 'rules/plot.smk'

# TODO 生成单样本报告
